"""Unit tests for ``ScheduleIntakeAgent``.

Spec: kb/07-MVP/Tech/03-Discussoes/schedule/01 - Spec SCHEDULE_INTAKE.md (§13).

Twelve canonical cases. LM mocked end-to-end (no DeepSeek calls).
"""

from __future__ import annotations

import json
from typing import Any, Dict, List
from unittest.mock import MagicMock

import pytest


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


CLINIC = "clinic-uuid-1"


def _q(qid: str, order: int, category: str, text: str, required: bool = True, source: str = "clinic"):
    return {
        "id": qid,
        "order": order,
        "question_text": text,
        "category": category,
        "is_required": required,
        "source": source,
    }


@pytest.fixture
def five_baseline_questions() -> List[Dict[str, Any]]:
    return [
        _q("q-med-001", 1, "medicamentos", "Você toma algum medicamento regularmente?"),
        _q("q-alg-002", 2, "alergias", "Tem alguma alergia conhecida?"),
        _q("q-gest-003", 3, "gestacao", "Está grávida ou amamentando?"),
        _q("q-cron-004", 4, "cronicas", "Tem doença crônica como diabetes, pressão alta etc?"),
        _q("q-pele-005", 5, "pele", "Como está sua pele neste momento?"),
    ]


@pytest.fixture
def session_data_evaluation_botox() -> List[Dict[str, Any]]:
    return [{"name": "evaluation", "data": {"service": "botox", "intake_answers": []}}]


def _mock_lm_returning(*payloads: Dict[str, Any]) -> MagicMock:
    """Return a MagicMock LM that yields the given JSON payloads in order.

    Each LM call returns a list with the next JSON string. Used to simulate
    multi-turn flows in a single test.
    """
    lm = MagicMock()
    side_effects = [[json.dumps(p)] for p in payloads]
    lm.side_effect = side_effects
    return lm


# Empty LM mock — when the agent does NOT call the LM (e.g. cold start
# generation only, or empty-questions short-circuit). We still allow it being
# invoked once for natural variant generation.
def _mock_lm_text(text: str) -> MagicMock:
    lm = MagicMock()
    lm.return_value = [
        json.dumps(
            {
                "next_question_text": text,
                "parsed_answers": [],
                "reasoning": "cold start",
            }
        )
    ]
    return lm


# ---------------------------------------------------------------------------
# Case 1: Cold start (no prior answers, no patient reply yet)
# ---------------------------------------------------------------------------


class TestCase01_ColdStart:
    def test_cold_start_asks_first_question(
        self, five_baseline_questions, session_data_evaluation_botox
    ):
        from app.agents.schedule_intake.agent import ScheduleIntakeAgent

        lm = _mock_lm_text("Pra começar, você toma algum medicamento regularmente?")
        agent = ScheduleIntakeAgent(lm=lm)

        out = agent.forward(
            latest_message="",
            history=[],
            session_data=session_data_evaluation_botox,
            clinic_id=CLINIC,
            service="botox",
            questions=five_baseline_questions,
            contraindications=["gravidez", "anticoagulante"],
        )

        assert out["conversation_stage"] == "schedule_intake"
        assert out["data"]["sub_intent_complete"] is False
        assert out["data"]["next_hint"] is None
        assert out["data"]["next_question_id"] == "q-med-001"
        assert out["data"]["intake_answers"] == []
        # Message generated by LM is in output
        assert out["messages"][0]["type"] == "text"
        assert "medicamento" in out["messages"][0]["content"].lower()


# ---------------------------------------------------------------------------
# Case 9: Empty questions list -> immediate completion (no LM call)
# ---------------------------------------------------------------------------


class TestCase09_EmptyQuestions:
    def test_empty_questions_completes_immediately(self, session_data_evaluation_botox):
        from app.agents.schedule_intake.agent import ScheduleIntakeAgent

        lm = MagicMock()  # must NOT be called
        agent = ScheduleIntakeAgent(lm=lm)

        out = agent.forward(
            latest_message="",
            history=[],
            session_data=session_data_evaluation_botox,
            clinic_id=CLINIC,
            service="botox",
            questions=[],
            contraindications=["gravidez"],
        )

        assert out["data"]["sub_intent_complete"] is True
        assert out["data"]["next_hint"] is None
        assert out["data"]["next_question_id"] is None
        assert out["data"]["intake_answers"] == []
        lm.assert_not_called()


# ---------------------------------------------------------------------------
# Case 2: Happy path completion (last question already answered)
# ---------------------------------------------------------------------------


class TestCase02_HappyPathCompletion:
    def test_all_required_answered_no_escalation_completes(
        self, five_baseline_questions, session_data_evaluation_botox
    ):
        from app.agents.schedule_intake.agent import ScheduleIntakeAgent

        # Pre-fill all 5 answers in session_data; LM parses the 5th answer last turn.
        prior_answers = [
            {
                "question_id": q["id"],
                "question_text": q["question_text"],
                "category": q["category"],
                "answer": "não",
                "matched_contraindication": None,
            }
            for q in five_baseline_questions[:4]  # first 4 answered
        ]
        session_data_evaluation_botox[0]["data"]["intake_answers"] = prior_answers

        # LM parses last (5th) answer: pele is fine.
        lm = _mock_lm_returning(
            {
                "next_question_text": "",  # no next question
                "parsed_answers": [
                    {
                        "question_id": "q-pele-005",
                        "answer": "tá boa",
                        "matched_contraindication": None,
                    }
                ],
                "reasoning": "5a resposta parseada; intake completo",
            }
        )
        agent = ScheduleIntakeAgent(lm=lm)

        out = agent.forward(
            latest_message="tá boa, normal",
            history=[
                {"role": "assistant", "content": "Como está sua pele?"},
                {"role": "human", "content": "tá boa, normal"},
            ],
            session_data=session_data_evaluation_botox,
            clinic_id=CLINIC,
            service="botox",
            questions=five_baseline_questions,
            contraindications=["gravidez", "anticoagulante"],
        )

        assert out["data"]["sub_intent_complete"] is True
        assert out["data"]["next_hint"] is None
        assert out["data"]["next_question_id"] is None
        assert len(out["data"]["intake_answers"]) == 5


# ---------------------------------------------------------------------------
# Case 3: Pregnancy detected -> escalate
# ---------------------------------------------------------------------------


class TestCase03_PregnancyEscalation:
    def test_pregnancy_match_escalates(
        self, five_baseline_questions, session_data_evaluation_botox
    ):
        from app.agents.schedule_intake.agent import ScheduleIntakeAgent

        prior = [
            {
                "question_id": "q-med-001",
                "question_text": five_baseline_questions[0]["question_text"],
                "category": "medicamentos",
                "answer": "não",
                "matched_contraindication": None,
            },
            {
                "question_id": "q-alg-002",
                "question_text": five_baseline_questions[1]["question_text"],
                "category": "alergias",
                "answer": "não",
                "matched_contraindication": None,
            },
        ]
        session_data_evaluation_botox[0]["data"]["intake_answers"] = prior

        lm = _mock_lm_returning(
            {
                "next_question_text": "",
                "parsed_answers": [
                    {
                        "question_id": "q-gest-003",
                        "answer": "sim, estou grávida de 12 semanas",
                        "matched_contraindication": "gravidez",
                    }
                ],
                "reasoning": "gravidez detectada, escalando",
            }
        )
        agent = ScheduleIntakeAgent(lm=lm)

        out = agent.forward(
            latest_message="sim, estou grávida de 12 semanas",
            history=[
                {"role": "assistant", "content": "Está grávida ou amamentando?"},
                {"role": "human", "content": "sim, estou grávida de 12 semanas"},
            ],
            session_data=session_data_evaluation_botox,
            clinic_id=CLINIC,
            service="botox",
            questions=five_baseline_questions,
            contraindications=["gravidez", "anticoagulante"],
        )

        assert out["data"]["next_hint"] == "ESCALATE_TO_HUMAN"
        assert out["data"]["sub_intent_complete"] is False
        assert out["data"]["next_question_id"] is None
        last_answer = out["data"]["intake_answers"][-1]
        assert last_answer["matched_contraindication"] == "gravidez"
        assert "gravidez" in out["data"]["escalation_reason"].lower()


# ---------------------------------------------------------------------------
# Case 4: Anticoagulant by medication name (warfarina)
# ---------------------------------------------------------------------------


class TestCase04_AnticoagulantByName:
    def test_warfarina_maps_to_anticoagulante(
        self, five_baseline_questions, session_data_evaluation_botox
    ):
        from app.agents.schedule_intake.agent import ScheduleIntakeAgent

        lm = _mock_lm_returning(
            {
                "next_question_text": "",
                "parsed_answers": [
                    {
                        "question_id": "q-med-001",
                        "answer": "tomo warfarina",
                        "matched_contraindication": "anticoagulante",
                    }
                ],
                "reasoning": "warfarina = anticoagulante",
            }
        )
        agent = ScheduleIntakeAgent(lm=lm)

        out = agent.forward(
            latest_message="tomo warfarina",
            history=[
                {"role": "assistant", "content": "Toma algum medicamento?"},
                {"role": "human", "content": "tomo warfarina"},
            ],
            session_data=session_data_evaluation_botox,
            clinic_id=CLINIC,
            service="botox",
            questions=five_baseline_questions,
            contraindications=["anticoagulante", "gravidez"],
        )

        assert out["data"]["next_hint"] == "ESCALATE_TO_HUMAN"
        assert out["data"]["intake_answers"][-1]["matched_contraindication"] == "anticoagulante"


# ---------------------------------------------------------------------------
# Case 5: Colloquial synonym ("tô esperando neném" -> gravidez)
# ---------------------------------------------------------------------------


class TestCase05_ColloquialSynonym:
    def test_colloquial_pregnancy_synonym_escalates(
        self, five_baseline_questions, session_data_evaluation_botox
    ):
        from app.agents.schedule_intake.agent import ScheduleIntakeAgent

        # Pretend 2 prior answered: med + alg. Patient now answers gestation question.
        session_data_evaluation_botox[0]["data"]["intake_answers"] = [
            {
                "question_id": "q-med-001",
                "question_text": "Você toma algum medicamento regularmente?",
                "category": "medicamentos",
                "answer": "não",
                "matched_contraindication": None,
            },
            {
                "question_id": "q-alg-002",
                "question_text": "Tem alguma alergia conhecida?",
                "category": "alergias",
                "answer": "não",
                "matched_contraindication": None,
            },
        ]

        lm = _mock_lm_returning(
            {
                "next_question_text": "",
                "parsed_answers": [
                    {
                        "question_id": "q-gest-003",
                        "answer": "tô esperando neném",
                        "matched_contraindication": "gravidez",
                    }
                ],
                "reasoning": "gíria de gravidez",
            }
        )
        agent = ScheduleIntakeAgent(lm=lm)

        out = agent.forward(
            latest_message="tô esperando neném",
            history=[
                {"role": "assistant", "content": "Está grávida ou amamentando?"},
                {"role": "human", "content": "tô esperando neném"},
            ],
            session_data=session_data_evaluation_botox,
            clinic_id=CLINIC,
            service="botox",
            questions=five_baseline_questions,
            contraindications=["gravidez", "anticoagulante"],
        )

        assert out["data"]["next_hint"] == "ESCALATE_TO_HUMAN"
        assert out["data"]["intake_answers"][-1]["matched_contraindication"] == "gravidez"


# ---------------------------------------------------------------------------
# Case 6: Patient refuses ("prefiro não dizer")
# ---------------------------------------------------------------------------


class TestCase06_PatientRefuses:
    def test_refusal_recorded_and_proceeds(
        self, five_baseline_questions, session_data_evaluation_botox
    ):
        from app.agents.schedule_intake.agent import ScheduleIntakeAgent

        lm = _mock_lm_returning(
            {
                "next_question_text": "Tem alguma alergia conhecida?",
                "parsed_answers": [
                    {
                        "question_id": "q-med-001",
                        "answer": "prefiro não dizer",
                        "matched_contraindication": None,
                    }
                ],
                "reasoning": "paciente recusou; segue próxima",
            }
        )
        agent = ScheduleIntakeAgent(lm=lm)

        out = agent.forward(
            latest_message="prefiro não dizer",
            history=[
                {"role": "assistant", "content": "Toma algum medicamento?"},
                {"role": "human", "content": "prefiro não dizer"},
            ],
            session_data=session_data_evaluation_botox,
            clinic_id=CLINIC,
            service="botox",
            questions=five_baseline_questions,
            contraindications=["gravidez", "anticoagulante"],
        )

        assert out["data"]["sub_intent_complete"] is False
        assert out["data"]["next_hint"] is None
        # Answer recorded
        assert any(
            a["question_id"] == "q-med-001" and "prefiro" in a["answer"]
            for a in out["data"]["intake_answers"]
        )
        # Advanced to next required question
        assert out["data"]["next_question_id"] == "q-alg-002"


# ---------------------------------------------------------------------------
# Case 7: Multi-answer single turn
# ---------------------------------------------------------------------------


class TestCase07_MultiAnswer:
    def test_three_answers_in_one_turn(
        self, five_baseline_questions, session_data_evaluation_botox
    ):
        from app.agents.schedule_intake.agent import ScheduleIntakeAgent

        lm = _mock_lm_returning(
            {
                "next_question_text": "Tem doença crônica como diabetes ou pressão alta?",
                "parsed_answers": [
                    {
                        "question_id": "q-med-001",
                        "answer": "não tomo remédio",
                        "matched_contraindication": None,
                    },
                    {
                        "question_id": "q-alg-002",
                        "answer": "não tenho alergia",
                        "matched_contraindication": None,
                    },
                    {
                        "question_id": "q-gest-003",
                        "answer": "não estou grávida",
                        "matched_contraindication": None,
                    },
                ],
                "reasoning": "tres respostas extraidas com confianca >= 0.70",
            }
        )
        agent = ScheduleIntakeAgent(lm=lm)

        out = agent.forward(
            latest_message="não tomo remédio nenhum, nem tenho alergia, nem estou grávida",
            history=[
                {"role": "assistant", "content": "Toma algum medicamento?"},
                {
                    "role": "human",
                    "content": "não tomo remédio nenhum, nem tenho alergia, nem estou grávida",
                },
            ],
            session_data=session_data_evaluation_botox,
            clinic_id=CLINIC,
            service="botox",
            questions=five_baseline_questions,
            contraindications=["gravidez", "anticoagulante"],
        )

        assert len(out["data"]["intake_answers"]) == 3
        assert out["data"]["next_question_id"] == "q-cron-004"
        assert out["data"]["sub_intent_complete"] is False


# ---------------------------------------------------------------------------
# Case 8: Topic change ("quanto custa?") -> still re-asks current question.
# ---------------------------------------------------------------------------


class TestCase08_TopicChange:
    def test_topic_change_does_not_advance(
        self, five_baseline_questions, session_data_evaluation_botox
    ):
        from app.agents.schedule_intake.agent import ScheduleIntakeAgent

        # LM returns no parsed answers (patient changed topic) and re-asks the
        # same question.
        lm = _mock_lm_returning(
            {
                "next_question_text": "Antes de falar de valores, me confirma: você toma algum medicamento regularmente?",
                "parsed_answers": [],
                "reasoning": "paciente mudou de assunto; re-pergunta atual",
            }
        )
        agent = ScheduleIntakeAgent(lm=lm)

        out = agent.forward(
            latest_message="quanto custa?",
            history=[
                {"role": "assistant", "content": "Você toma algum medicamento?"},
                {"role": "human", "content": "quanto custa?"},
            ],
            session_data=session_data_evaluation_botox,
            clinic_id=CLINIC,
            service="botox",
            questions=five_baseline_questions,
            contraindications=["gravidez", "anticoagulante"],
        )

        # Still on q-med-001
        assert out["data"]["next_question_id"] == "q-med-001"
        assert out["data"]["sub_intent_complete"] is False
        assert out["data"]["intake_answers"] == []


# ---------------------------------------------------------------------------
# Case 10: Service override + clinic baseline (7 questions union)
# ---------------------------------------------------------------------------


class TestCase10_ServiceOverridePlusBaseline:
    def test_union_seven_questions(self, five_baseline_questions, session_data_evaluation_botox):
        from app.agents.schedule_intake.agent import ScheduleIntakeAgent

        service_qs = [
            _q("q-svc-006", 6, "historico", "Já fez botox antes?", source="service"),
            _q("q-svc-007", 7, "historico", "Última aplicação quando?", source="service"),
        ]
        all_questions = five_baseline_questions + service_qs

        lm = _mock_lm_text("Pra começar, você toma algum medicamento regularmente?")
        agent = ScheduleIntakeAgent(lm=lm)

        out = agent.forward(
            latest_message="",
            history=[],
            session_data=session_data_evaluation_botox,
            clinic_id=CLINIC,
            service="botox",
            questions=all_questions,
            contraindications=["gravidez"],
        )

        # First question is order=1
        assert out["data"]["next_question_id"] == "q-med-001"
        assert out["data"]["sub_intent_complete"] is False
        # Internally agent did not lose service-specific entries: they will be
        # asked after baseline finishes. Sanity-check via answers count target:
        # not directly observable, but the lookup order can be tested by
        # answering all baseline and verifying next_question advances to q-svc-006.


# ---------------------------------------------------------------------------
# Case 11: Contraindications empty -> no escalation even with sensitive answer
# ---------------------------------------------------------------------------


class TestCase11_EmptyContraindications:
    def test_no_escalation_when_contraindications_empty(
        self, five_baseline_questions, session_data_evaluation_botox
    ):
        from app.agents.schedule_intake.agent import ScheduleIntakeAgent

        session_data_evaluation_botox[0]["data"]["intake_answers"] = [
            {
                "question_id": "q-med-001",
                "question_text": "Toma medicamento?",
                "category": "medicamentos",
                "answer": "não",
                "matched_contraindication": None,
            },
            {
                "question_id": "q-alg-002",
                "question_text": "Tem alergia?",
                "category": "alergias",
                "answer": "não",
                "matched_contraindication": None,
            },
        ]

        # LM returns matched_contraindication=null because list is empty.
        lm = _mock_lm_returning(
            {
                "next_question_text": "Tem doença crônica como diabetes, pressão alta etc?",
                "parsed_answers": [
                    {
                        "question_id": "q-gest-003",
                        "answer": "estou grávida",
                        "matched_contraindication": None,
                    }
                ],
                "reasoning": "lista de contraindicacoes vazia; nao escala",
            }
        )
        agent = ScheduleIntakeAgent(lm=lm)

        out = agent.forward(
            latest_message="estou grávida",
            history=[
                {"role": "assistant", "content": "Está grávida ou amamentando?"},
                {"role": "human", "content": "estou grávida"},
            ],
            session_data=session_data_evaluation_botox,
            clinic_id=CLINIC,
            service="botox",
            questions=five_baseline_questions,
            contraindications=[],  # KEY: empty
        )

        assert out["data"]["next_hint"] is None
        assert out["data"]["intake_answers"][-1]["matched_contraindication"] is None
        assert out["data"]["next_question_id"] == "q-cron-004"


# ---------------------------------------------------------------------------
# Case 12: False-positive favor (ambiguous answer -> still escalates)
# ---------------------------------------------------------------------------


class TestCase12_FalsePositiveFavor:
    def test_ambiguous_quimio_history_escalates(
        self, five_baseline_questions, session_data_evaluation_botox
    ):
        from app.agents.schedule_intake.agent import ScheduleIntakeAgent

        prior = [
            {
                "question_id": f"q-{i}",
                "question_text": "x",
                "category": "x",
                "answer": "não",
                "matched_contraindication": None,
            }
            for i in ("med-001", "alg-002", "gest-003")
        ]
        session_data_evaluation_botox[0]["data"]["intake_answers"] = prior

        lm = _mock_lm_returning(
            {
                "next_question_text": "",
                "parsed_answers": [
                    {
                        "question_id": "q-cron-004",
                        "answer": "fiz quimio ano passado",
                        "matched_contraindication": "câncer ativo",
                    }
                ],
                "reasoning": "ambiguo; conservadorismo clinico favorece escalar",
            }
        )
        agent = ScheduleIntakeAgent(lm=lm)

        out = agent.forward(
            latest_message="fiz quimio ano passado",
            history=[
                {"role": "assistant", "content": "Tem doença crônica?"},
                {"role": "human", "content": "fiz quimio ano passado"},
            ],
            session_data=session_data_evaluation_botox,
            clinic_id=CLINIC,
            service="botox",
            questions=five_baseline_questions,
            contraindications=["câncer ativo", "gravidez"],
        )

        assert out["data"]["next_hint"] == "ESCALATE_TO_HUMAN"
        last = out["data"]["intake_answers"][-1]
        assert last["matched_contraindication"] == "câncer ativo"
        assert "câncer ativo" in out["data"]["escalation_reason"].lower()


# ---------------------------------------------------------------------------
# Cross-cutting: input-validation guards
# ---------------------------------------------------------------------------


class TestInputValidation:
    def test_missing_evaluation_entry_raises(self, five_baseline_questions):
        from app.agents.schedule_intake.agent import ScheduleIntakeAgent

        lm = MagicMock()
        agent = ScheduleIntakeAgent(lm=lm)

        with pytest.raises(ValueError, match="evaluation"):
            agent.forward(
                latest_message="",
                history=[],
                session_data=[],  # missing
                clinic_id=CLINIC,
                service="botox",
                questions=five_baseline_questions,
                contraindications=[],
            )

    def test_missing_service_in_session_data_raises(self, five_baseline_questions):
        from app.agents.schedule_intake.agent import ScheduleIntakeAgent

        lm = MagicMock()
        agent = ScheduleIntakeAgent(lm=lm)

        with pytest.raises(ValueError, match="service"):
            agent.forward(
                latest_message="",
                history=[],
                session_data=[{"name": "evaluation", "data": {}}],  # no service key
                clinic_id=CLINIC,
                service="botox",
                questions=five_baseline_questions,
                contraindications=[],
            )

    def test_malformed_question_raises(self, session_data_evaluation_botox):
        from app.agents.schedule_intake.agent import ScheduleIntakeAgent

        lm = MagicMock()
        agent = ScheduleIntakeAgent(lm=lm)

        with pytest.raises(ValueError, match="malformed"):
            agent.forward(
                latest_message="",
                history=[],
                session_data=session_data_evaluation_botox,
                clinic_id=CLINIC,
                service="botox",
                questions=[{"id": "q1"}],  # missing order/text/category
                contraindications=[],
            )
